# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['swan_detector/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[('swan_detector/model/weights/model.pt', 'swan_detector/model/weights/')],
    hiddenimports=[
                'altgraph',
                'auto_py_to_exe',
                'bottle',
                'bottle.ext.websocket',
                'certifi',
                'charset_normalizer',
                'click',
                'cmake',
                'contourpy',
                'cycler',
                'eel',
                'filelock',
                'fonttools',
                'future',
                'gevent',
                'geventwebsocket',
                'greenlet',
                'idna',
                'jinja2',
                'kiwisolver',
                'lit',
                'markupsafe',
                'matplotlib',
                'mpmath',
                'networkx',
                'numpy',
                'nvidia.cuda.cublas',
                'nvidia.cuda.cupti',
                'nvidia.cuda.nvrtc',
                'nvidia.cuda.runtime',
                'nvidia.cuda.toolkit',
                'nvidia.cudnn',
                'nvidia.cufft',
                'nvidia.curand',
                'nvidia.cusolver',
                'nvidia.cusparse',
                'nvidia.nccl',
                'nvidia.nvtx',
                'packaging',
                'pandas',
                'PIL',
                'psutil',
                'PyInstaller',
                'PyInstaller.utils.hooks',
                'pyparsing',
                'PyQt5',
                'PyQt5.Qt',
                'PyQt5.sip',
                'pyqt5ac',
                'python_dateutil',
                'pytz',
                'PyYAML',
                'requests',
                'scipy',
                'seaborn',
                'sentry_sdk',
                'six',
                'sympy',
                'torch',
                'torchvision',
                'tqdm',
                'tritonclient',
                'typing_extensions',
                'tzdata',
                'ultralytics',
                'urllib3',
                'whichcraft',
                'zope.event',
                'zope.interface'
             ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['swan_detector/qt'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SwanDetector',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SwanDetector',
)
